publish_mode: editorial_workflow

backend:
  name: github
  repo: dgtlntv/vanilla-decap-monorepo # Path to your Github/Gitlab repository
  branch: main # Branch to update
  open_authoring: true
  base_url: https://auth.dgtln.tv # Path to ext auth provider

media_folder: 'images/uploads' # Media files will be stored in the repo under images/uploads

collections:
  - name: 'base'
    label: 'Base'
    folder: 'vanilla/templates/docs/base'
    create: true
    slug: '{{slug}}'
    fields:
      - label: 'Context'
        name: 'context'
        collapse: false
        widget: object
        fields:
          - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Body', name: 'body', widget: 'markdown'}
    identifier_field: 'context.title'
  - name: 'layouts'
    label: 'Layouts'
    folder: 'vanilla/templates/docs/layouts'
    create: true
    slug: '{{slug}}'
    fields:
      - label: 'Context'
        name: 'context'
        collapse: false
        widget: object
        fields:
          - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Body', name: 'body', widget: 'markdown'}
    identifier_field: 'context.title'
  - name: 'patterns'
    label: 'Patterns'
    folder: 'vanilla/templates/docs/patterns'
    create: true
    slug: '{{slug}}'
    fields:
      - label: 'Context'
        name: 'context'
        collapse: false
        widget: object
        fields:
          - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Body', name: 'body', widget: 'markdown'}
    identifier_field: 'context.title'
  - name: 'settings'
    label: 'Settings'
    folder: 'vanilla/templates/docs/settings'
    create: true
    slug: '{{slug}}'
    fields:
      - label: 'Context'
        name: 'context'
        collapse: false
        widget: object
        fields:
          - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Body', name: 'body', widget: 'markdown'}
    identifier_field: 'context.title'
  - name: 'utilities'
    label: 'Utilities'
    folder: 'vanilla/templates/docs/utilities'
    create: true
    slug: '{{slug}}'
    fields:
      - label: 'Context'
        name: 'context'
        collapse: false
        widget: object
        fields:
          - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Body', name: 'body', widget: 'markdown'}
    identifier_field: 'context.title'
